/*

White Rabbit Softcore PLL (SoftPLL) - common definitions

*/


#include <stdio.h>

/* Reference clock frequency */
#define CLOCK_FREQ 125000000

/* Bit size of phase tags generated by the DMTDs. Used to sign-extend the tags. */
#define TAG_BITS 20

/* Helper PLL N divider (1/2**N is the frequency offset) */
#define HPLL_N 14

/* Fractional bits in PI controller coefficients */
#define PI_FRACBITS 12

