---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version: '1.0.0'
name: 'FMC DEL 1ns 4cha'
description: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-delay-1ns-8cha/Home.md'
website: 'https://ohwr.org/project/fmc-delay-1ns-8cha'
licenses:
  - 'CC-BY-SA-4.0'
  - 'CERN-OHL-W-2.0'
  - 'GPL-2.0-or-later'
  - 'LGPL-2.1-or-later'
images:
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/bd03006106ad4b9aa220ac35dd0ec1f6/delay-v5-big.jpg'
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/5e2716e782e548bd1cfa3edface5f45c/proto_side_b_s.JPG'
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/041cda93bc8029760d2e5f6b1d72ec69/proto_side_a_s.JPG'
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/7be94eac5b88e295faebc7ae8a5999f2/frontpanel1.jpg'
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/2f8b9bf22ff2d0a24ef04e0b7beb8056/frontpanel2.jpg'
  - 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/a619d95e21b84c80ccd8eceb5dbb7caa/delay-v5-small.jpg'
documentation: 'https://ohwr.org/project/fmc-delay-1ns-8cha/wikis'
issues: 'https://ohwr.org/project/fmc-delay-1ns-8cha/issues'
latest_release: 'https://ohwr.org/project/fmc-delay-1ns-8cha/tags/v3.0.9'
forum: 'https://forums.ohwr.org/c/fmc-delay-1ns-8cha'
newsfeed: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-delay-1ns-8cha/News.md'
links:
  - name: 'FMC Delay 1ns 4cha Technical Specification v1.2'
    url: 'https://ohwr.org/project/fmc-delay-1ns-8cha/uploads/364be2448542f8ef28b8da276df0436c/FMC_delay_1ns_4_CH_spec.pdf'
  - name: 'Functional system specifications'
    url: 'https://ohwr.org/project/fmc-delay-1ns-8cha/wikis/FmcDelFuncSpec'
  - name: 'Documentation for the release v2014.04'
    url: 'https://ohwr.org/project/fine-delay-sw/uploads/7905f7ec91764a85e20f0473d6e6fe3f/fine-delay-sw-v2014-04.pdf'
  - name: 'hw/sw manual for v1.1 of the software'
    url: 'https://ohwr.org/project/fine-delay-sw/uploads/c2683683b513811ae49437384ec37e73/fine-delay-sw-v1.1.pdf'
  - name: 'Fine Delay - INCAA Computers, Netherlands'
    url: 'http://www.incaacomputers.com/products/fine-delay/'
