#!/bin/bash

repo_name=$1
repo_path=$2


if [ "$repo_path" != "" ]; then
	echo "Using user-supplied submodule path for $repo_name [$repo_path]" 1>&2
	path=$repo_path
elif [ -d "../$repo_name" ]; then
	echo "Using Git repo in parent directory for $repo_name [../$repo_name]" 1>&2
	path="../$repo_name"
else
	echo "Using local submodule checkout for $repo_name" 1>&2 
	git submodule update --init $repo_name 1>&2 
	path=$repo_name
fi

echo `readlink -f $path`